name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Modify Vite config for GitHub Pages
      run: |
        # Update vite.config.ts to include the base option for GitHub Pages
        sed -i "s/export default defineConfig({/export default defineConfig({\n  base: '\/selfportfolio\/',/g" vite.config.ts
      
    - name: Build with Vite
      run: |
        # Create .env file with BASE_URL
        echo "VITE_BASE_URL=/selfportfolio/" > .env
        # Run the build command 
        npm run build
        # Create .nojekyll file
        touch dist/public/.nojekyll
        # Copy 404.html to handle client-side routing
        cp client/public/404.html dist/public/404.html
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to
        folder: dist/public # The folder the action should deploy
        clean: true # Automatically remove deleted files from the deployment branch